---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[jenkins::default]
    attributes: 
      nginx_port: 8080,
      tomcat_port: 10080,
      jenkins_port: 9080
