Vagrant.configure(2) do |config|
	config.vm.box = "sbeliakou/centos-6.7-x86_64"
	config.vm.provision "shell", path: "provision.sh"
	config.vm.network :private_network, ip: "192.168.133.50"

	config.vm.hostname = "Petchef02"
  
	config.vm.provider "virtualbox" do |vb|
		vb.name = "Chef"                
	end
end
