# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "sbeliakou/centos-6.7-x86_64"  
  config.vm.network "private_network", ip: "192.168.15.20"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.hostname = "test"  
  config.vm.provider "virtualbox" do |vb|
    vb = config.vm.hostname
  end
  config.vm.provision "shell", path: "scr/provision.sh"
  config.vm.provision "shell", inline: "echo The Apache-server is DONE!"
end
